apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test-4
  namespace: stress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-test-4
  template:
    metadata:
      labels:
        app: stress-test-4
    spec:
      containers:
      - name: stress-test-4
        image: ubuntu:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            apt-get update && apt-get install -y stress-ng && 
            while true; do
              echo "Starting Mixed CPU and Memory Workload stress test..."
              stress-ng --cpu 2 --cpu-method matrixprod --vm 2 --vm-bytes 256M --timeout 120s
              echo "Mixed CPU and Memory Workload stress test complete. Sleeping for 1 minute..."
              sleep 3600
            done
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"

